meta_product_name: "Nurse Planning"
meta_title: "Nurse Planning - Le compagnon de tournée des infirmières libérales"
meta_description: "Gestion de la patientèle, des visites et du planning."
meta_image: "logo.png"
twitter_account: "@nurse-planning"
